module.exports = {
  GET_SUCCESS:    0,
  GET_FAIL:       1,
  POST_SUCCESS:   20,
  POST_FAIL:      21,
  PUT_SUCCESS:    40,
  PUT_FAIL:       41,
  DELETE_SUCCESS: 60,
  DELETE_FAIL:    61,
  PARAMS_INSUFF:  100,
  INVALID_QUERY_STRING: 101
};
